import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    'overview/intro',
    'overview/embodied-ai-roadmap',
    'overview/learning-path',
    'overview/company-landscape',
    'overview/robotics-and-ros2-roadmap',
    'overview/algorithm-engineer-transition',
  ],

  foundationsSidebar: [
    'foundations/intro',
    {
      type: 'category',
      label: '具身智能入门',
      items: [{ type: 'autogenerated', dirName: 'foundations/embodied-ai-intro' }],
    },
    {
      type: 'category',
      label: '机器人运动学与 ROS2 基础',
      link: { type: 'doc', id: 'foundations/robotics-basics/intro' },
      items: [
        { type: 'doc', id: 'foundations/robotics-basics/course_introduction', label: '1. 系统导览与机器人系统全景' },
        { type: 'doc', id: 'foundations/robotics-basics/kinematics_transform', label: '2. 运动学核心概念与坐标变换' },
        { type: 'doc', id: 'foundations/robotics-basics/fk_ik_implementation', label: '3. 正运动学与逆运动学实现' },
        { type: 'doc', id: 'foundations/ros2-basics/ros2_engineering_basics', label: '4. ROS2 工程基础' },
        { type: 'doc', id: 'foundations/ros2-basics/topics', label: '5. 话题通信 Topic' },
        { type: 'doc', id: 'foundations/ros2-basics/services_actions', label: '6. 服务通信 Service 与动作 Action' },
        { type: 'doc', id: 'foundations/ros2-basics/parameters_launch', label: '7. 参数系统与 Launch 文件' },
        { type: 'doc', id: 'foundations/ros2-basics/tf2', label: '8. tf2 坐标变换管理' },
        { type: 'doc', id: 'foundations/ros2-basics/urdf_and_rsp', label: '9. URDF 建模与 robot_state_publisher' },
        { type: 'doc', id: 'foundations/ros2-basics/moveit2_basics', label: '10. MoveIt 2 基础与运动规划' },
        { type: 'doc', id: 'foundations/ros2-basics/moveit2_project', label: '11. MoveIt 2 仿真项目实战' },
        { type: 'doc', id: 'foundations/ros2-basics/summary_and_next_steps', label: '12. 课程总结与进阶方向' },
      ],
    },
    {
      type: 'category',
      label: '仿真工具基础',
      items: [{ type: 'autogenerated', dirName: 'foundations/simulation' }],
    },
    {
      type: 'category',
      label: '强化学习与控制',
      items: [{ type: 'autogenerated', dirName: 'foundations/rl-for-robotics' }],
    },
    {
      type: 'category',
      label: '数据采集与模仿学习',
      items: [{ type: 'autogenerated', dirName: 'foundations/imitation-learning' }],
    },
    {
      type: 'category',
      label: 'VLM / VLA / World Model',
      items: [{ type: 'autogenerated', dirName: 'foundations/vlm-vla-world-model' }],
    },
  ],

  practicesSidebar: [
    'practices/intro',
    {
      type: 'category',
      label: '机械臂方向',
      items: [{ type: 'autogenerated', dirName: 'practices/robot-arm' }],
    },
    {
      type: 'category',
      label: '四足机器人',
      items: [{ type: 'autogenerated', dirName: 'practices/quadruped' }],
    },
    {
      type: 'category',
      label: '双足 / 人形机器人',
      items: [{ type: 'autogenerated', dirName: 'practices/humanoid' }],
    },
    {
      type: 'category',
      label: '移动操作',
      items: [{ type: 'autogenerated', dirName: 'practices/mobile-manipulation' }],
    },
  ],

  careerSidebar: [
    'career/intro',
    {
      type: 'category',
      label: '岗位技能拆解',
      items: [{ type: 'autogenerated', dirName: 'career/job-skill-map' }],
    },
    {
      type: 'category',
      label: '面经与八股',
      items: [{ type: 'autogenerated', dirName: 'career/interview-questions' }],
    },
    {
      type: 'category',
      label: '简历与作品集',
      items: [{ type: 'autogenerated', dirName: 'career/resume-portfolio' }],
    },
    {
      type: 'category',
      label: '公司技术栈',
      items: [{ type: 'autogenerated', dirName: 'career/company-tech-stacks' }],
    },
    {
      type: 'category',
      label: '招聘信息',
      items: [{ type: 'autogenerated', dirName: 'career/job-listings' }],
    },
    {
      type: 'category',
      label: '转岗路径',
      items: [{ type: 'autogenerated', dirName: 'career/transition-paths' }],
    },
    {
      type: 'category',
      label: '社区与内推',
      items: [{ type: 'autogenerated', dirName: 'career/community' }],
    },
  ],
};

export default sidebars;
