import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    'overview/intro',
    'overview/embodied-ai-roadmap',
    'overview/learning-path',
    'overview/company-landscape',
    'overview/robotics-and-ros2-roadmap',
    'overview/algorithm-engineer-transition',
  ],

  foundationsSidebar: [
    'foundations/intro',
    {
      type: 'category',
      label: '具身智能入门',
      items: [{ type: 'autogenerated', dirName: 'foundations/embodied-ai-intro' }],
    },
    {
      type: 'category',
      label: '机器人基础',
      items: [{ type: 'autogenerated', dirName: 'foundations/robotics-basics' }],
    },
    {
      type: 'category',
      label: 'ROS2 工程基础',
      items: [{ type: 'autogenerated', dirName: 'foundations/ros2-basics' }],
    },
    {
      type: 'category',
      label: '仿真工具基础',
      items: [{ type: 'autogenerated', dirName: 'foundations/simulation' }],
    },
    {
      type: 'category',
      label: '强化学习与控制',
      items: [{ type: 'autogenerated', dirName: 'foundations/rl-for-robotics' }],
    },
    {
      type: 'category',
      label: '数据采集与模仿学习',
      items: [{ type: 'autogenerated', dirName: 'foundations/imitation-learning' }],
    },
    {
      type: 'category',
      label: 'VLM / VLA / World Model',
      items: [{ type: 'autogenerated', dirName: 'foundations/vlm-vla-world-model' }],
    },
  ],

  practicesSidebar: [
    'practices/intro',
    {
      type: 'category',
      label: '机械臂方向',
      items: [{ type: 'autogenerated', dirName: 'practices/robot-arm' }],
    },
    {
      type: 'category',
      label: '四足机器人',
      items: [{ type: 'autogenerated', dirName: 'practices/quadruped' }],
    },
    {
      type: 'category',
      label: '双足 / 人形机器人',
      items: [{ type: 'autogenerated', dirName: 'practices/humanoid' }],
    },
    {
      type: 'category',
      label: '移动操作',
      items: [{ type: 'autogenerated', dirName: 'practices/mobile-manipulation' }],
    },
  ],

  careerSidebar: [
    'career/intro',
    {
      type: 'category',
      label: '岗位技能拆解',
      items: [{ type: 'autogenerated', dirName: 'career/job-skill-map' }],
    },
    {
      type: 'category',
      label: '面经与八股',
      items: [{ type: 'autogenerated', dirName: 'career/interview-questions' }],
    },
    {
      type: 'category',
      label: '简历与作品集',
      items: [{ type: 'autogenerated', dirName: 'career/resume-portfolio' }],
    },
    {
      type: 'category',
      label: '公司技术栈',
      items: [{ type: 'autogenerated', dirName: 'career/company-tech-stacks' }],
    },
    {
      type: 'category',
      label: '招聘信息',
      items: [{ type: 'autogenerated', dirName: 'career/job-listings' }],
    },
    {
      type: 'category',
      label: '转岗路径',
      items: [{ type: 'autogenerated', dirName: 'career/transition-paths' }],
    },
    {
      type: 'category',
      label: '社区与内推',
      items: [{ type: 'autogenerated', dirName: 'career/community' }],
    },
  ],
};

export default sidebars;
